 version: 0.2
 phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint
  build:
    commands:
      - REPORT=$(uuidgen)-cfnlint-report.json
      - set +e
      - cfn-lint -f json > $REPORT
      - aws s3 cp $REPORT s3://cfn-lint-bucketwa/
