 version: 0.2
 phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint
  build:
    commands:
      - REPORT=$(uuidgen)-cfnlint-report.json
      - set +e
      - cfn-lint -f json > $REPORT
      - echo "Copying to s3://$CFN_LINT_BUCKET/$AWS_ACCOUNT_ID/$(date +'%Y')/$(date +'%m')/$(date +'%d')"
